---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alitari/webservice-springboot-buildimage    

inputs:
- name: webservice-springboot

run:
  path: mvn
  args: 
  - -f
  - webservice-springboot
  - -s 
  - /usr/share/maven/ref/settings-docker.xml
  - clean
  - site