---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alitari/webservice-springboot-buildimage    

inputs:
- name: webservice-springboot

outputs:
- name: webservice-springboot-target

run:
  path: webservice-springboot/ci/scripts/site.sh
