#nexus:
#  image: sonatype/nexus
#  ports:
#    - "8081:8081"
#  volumes:
#    - /etc/nexus-data:/sonatype-work

#registry:
#  image: registry
#  ports:
#    - "5000:5000"
#  volumes:
#    - /etc/docker-registry:/tmp/registry-dev

#registry-ui:
#  image: atcol/docker-registry-ui
#  ports:
#    - "8080:8080"
#  environment:
#    - REG1=http://192.168.0.16:5000/v1/




sonarqube:
  image: sonarqube:5.1
  ports:
   - "9000:9000"
   - "5432:5432"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar

sonar-db:
  image: postgres
  net: container:sonarqube
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
   - /etc/postgres/sonar/data:/var/lib/postgresql/data

jenkins:
  build: jenkins
  user: root
  ports:
   - "8180:8080" 
   - "50000:50000"
  volumes:
   - /etc/jenkins_home:/var/jenkins_home
    
 
