nexus:
  image: sonatype/nexus
  ports:
    - "8081:8081"
  volumes:
    - /etc/nexus-data:/sonatype-work

registry:
  image: registry
  ports:
    - "5000:5000"
  volumes:
    - /etc/docker-registry:/tmp/registry-dev

registry-ui:
  image: atcol/docker-registry-ui
  ports:
    - "8080:8080"
  environment:
    - REG1=http://registry:5000/v1/
  extra_hosts:
   - "registry:192.168.0.16"


sonarqube:
  image: sonarqube:5.1
  ports:
   - "9000:9000"
   - "5432:5432"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar

sonar-db:
  image: postgres
  net: container:sonarqube
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
   - /etc/postgres/sonar/data:/var/lib/postgresql/data

jenkins:
  image: killercentury/jenkins-dind
  user: root
  ports:
   - "8180:8080"
   - "50000:50000"
  environment: 
   - DOCKER_DAEMON_ARGS="--insecure-registry registry:5000"
  volumes:
   - /etc/jenkins_home:/var/lib/jenkins   
  privileged: true
  extra_hosts:
   - "registry:192.168.0.16"
   
cadvisor:
  image: google/cadvisor:latest
  ports:
    - "8380:8080"
  volumes:
  - /:/rootfs:ro 
  - /var/run:/var/run:rw
  - /sys:/sys:ro
  - /var/lib/docker/:/var/lib/docker:ro
 
